package main

import (
  "fmt"
  "flag"
  "os"
  "time"
  
  "sluai/shikaku/shikakupuzzle"
  "sluai/shikaku/search"
)

func main() {
  problem := flag.Int("problem", 1, "problem id 1-8 of test puzzle")
  flag.Parse()
  
  if *problem < 1 || *problem > 8 {
    fmt.Printf("There problem must be from 1 to 8\n")
    os.Exit(0)
  }
   
  var p shikakupuzzle.ShikakuPuzzle
  switch *problem {
    case 1:
      p.Width = 3
      p.Height = 3
      p.NumRegions = 3
      p.RegionSize = make([]int, 3)
      p.RegionSize[0] = 6
      p.RegionSize[1] = 2
      p.RegionSize[2] = 1
      p.RegionLocation = make([]shikakupuzzle.Coordinate, 3)
      p.RegionLocation[0] = shikakupuzzle.Coordinate{ 2, 0 }
      p.RegionLocation[1] = shikakupuzzle.Coordinate{ 0, 1 }
      p.RegionLocation[2] = shikakupuzzle.Coordinate{ 0, 2 }
      
    case 2:
      p.Width = 5
      p.Height = 5
      p.NumRegions = 9
      p.RegionSize = make([]int, 9)
      p.RegionSize[0] = 3
      p.RegionSize[1] = 4
      p.RegionSize[2] = 2
      p.RegionSize[3] = 2
      p.RegionSize[4] = 2
      p.RegionSize[5] = 4
      p.RegionSize[6] = 2
      p.RegionSize[7] = 2
      p.RegionSize[8] = 4
      p.RegionLocation = make([]shikakupuzzle.Coordinate, 9)
      p.RegionLocation[0] = shikakupuzzle.Coordinate{ 0, 0 }
      p.RegionLocation[1] = shikakupuzzle.Coordinate{ 0, 3 }
      p.RegionLocation[2] = shikakupuzzle.Coordinate{ 1, 1 }
      p.RegionLocation[3] = shikakupuzzle.Coordinate{ 1, 2 }
      p.RegionLocation[4] = shikakupuzzle.Coordinate{ 2, 3 }
      p.RegionLocation[5] = shikakupuzzle.Coordinate{ 3, 1 }
      p.RegionLocation[6] = shikakupuzzle.Coordinate{ 3, 3 }
      p.RegionLocation[7] = shikakupuzzle.Coordinate{ 3, 4 }
      p.RegionLocation[8] = shikakupuzzle.Coordinate{ 4, 1 }

    case 3:
      p.Width = 7
      p.Height = 7
      p.NumRegions = 14
      p.RegionSize = make([]int, 14)
      p.RegionSize[0] = 2
      p.RegionSize[1] = 2
      p.RegionSize[2] = 3
      p.RegionSize[3] = 3
      p.RegionSize[4] = 3
      p.RegionSize[5] = 2
      p.RegionSize[6] = 2
      p.RegionSize[7] = 4
      p.RegionSize[8] = 6
      p.RegionSize[9] = 6
      p.RegionSize[10] = 8
      p.RegionSize[11] = 3
      p.RegionSize[12] = 3
      p.RegionSize[13] = 2
      p.RegionLocation = make([]shikakupuzzle.Coordinate, 14)
      p.RegionLocation[0] = shikakupuzzle.Coordinate{ 0, 1 }
      p.RegionLocation[1] = shikakupuzzle.Coordinate{ 0, 2 }
      p.RegionLocation[2] = shikakupuzzle.Coordinate{ 0, 6 }
      p.RegionLocation[3] = shikakupuzzle.Coordinate{ 1, 3 }
      p.RegionLocation[4] = shikakupuzzle.Coordinate{ 1, 5 }
      p.RegionLocation[5] = shikakupuzzle.Coordinate{ 2, 1 }
      p.RegionLocation[6] = shikakupuzzle.Coordinate{ 2, 2 }
      p.RegionLocation[7] = shikakupuzzle.Coordinate{ 2, 6 }
      p.RegionLocation[8] = shikakupuzzle.Coordinate{ 4, 0 }
      p.RegionLocation[9] = shikakupuzzle.Coordinate{ 4, 2 }
      p.RegionLocation[10] = shikakupuzzle.Coordinate{ 4, 3 }
      p.RegionLocation[11] = shikakupuzzle.Coordinate{ 4, 5 }
      p.RegionLocation[12] = shikakupuzzle.Coordinate{ 4, 6 }
      p.RegionLocation[13] = shikakupuzzle.Coordinate{ 6, 3 }

    case 4:
      p.Width = 10
      p.Height = 10
      p.NumRegions = 26
      p.RegionSize = make([]int, 26)
      p.RegionSize[0] = 2
      p.RegionSize[1] = 3
      p.RegionSize[2] = 3
      p.RegionSize[3] = 2
      p.RegionSize[4] = 2
      p.RegionSize[5] = 2
      p.RegionSize[6] = 3
      p.RegionSize[7] = 2
      p.RegionSize[8] = 3
      p.RegionSize[9] = 2
      p.RegionSize[10] = 2
      p.RegionSize[11] = 8
      p.RegionSize[12] = 4
      p.RegionSize[13] = 4
      p.RegionSize[14] = 4
      p.RegionSize[15] = 14
      p.RegionSize[16] = 2
      p.RegionSize[17] = 5
      p.RegionSize[18] = 8
      p.RegionSize[19] = 8
      p.RegionSize[20] = 4
      p.RegionSize[21] = 3
      p.RegionSize[22] = 3
      p.RegionSize[23] = 2
      p.RegionSize[24] = 3
      p.RegionSize[25] = 2
      p.RegionLocation = make([]shikakupuzzle.Coordinate, 26)
      p.RegionLocation[0] = shikakupuzzle.Coordinate{ 0, 0 }
      p.RegionLocation[1] = shikakupuzzle.Coordinate{ 0, 4 }
      p.RegionLocation[2] = shikakupuzzle.Coordinate{ 0, 8 }
      p.RegionLocation[3] = shikakupuzzle.Coordinate{ 1, 0 }
      p.RegionLocation[4] = shikakupuzzle.Coordinate{ 1, 2 }
      p.RegionLocation[5] = shikakupuzzle.Coordinate{ 1, 4 }
      p.RegionLocation[6] = shikakupuzzle.Coordinate{ 1, 6 }
      p.RegionLocation[7] = shikakupuzzle.Coordinate{ 1, 8 }
      p.RegionLocation[8] = shikakupuzzle.Coordinate{ 2, 5 }
      p.RegionLocation[9] = shikakupuzzle.Coordinate{ 2, 7 }
      p.RegionLocation[10] = shikakupuzzle.Coordinate{ 2, 8 }
      p.RegionLocation[11] = shikakupuzzle.Coordinate{ 3, 3 }
      p.RegionLocation[12] = shikakupuzzle.Coordinate{ 4, 3 }
      p.RegionLocation[13] = shikakupuzzle.Coordinate{ 4, 8 }
      p.RegionLocation[14] = shikakupuzzle.Coordinate{ 6, 3 }
      p.RegionLocation[15] = shikakupuzzle.Coordinate{ 6, 6 }
      p.RegionLocation[16] = shikakupuzzle.Coordinate{ 6, 8 }
      p.RegionLocation[17] = shikakupuzzle.Coordinate{ 7, 0 }
      p.RegionLocation[18] = shikakupuzzle.Coordinate{ 7, 1 }
      p.RegionLocation[19] = shikakupuzzle.Coordinate{ 7, 4 }
      p.RegionLocation[20] = shikakupuzzle.Coordinate{ 7, 5 }
      p.RegionLocation[21] = shikakupuzzle.Coordinate{ 7, 8 }
      p.RegionLocation[22] = shikakupuzzle.Coordinate{ 7, 9 }
      p.RegionLocation[23] = shikakupuzzle.Coordinate{ 8, 5 }
      p.RegionLocation[24] = shikakupuzzle.Coordinate{ 9, 2 }
      p.RegionLocation[25] = shikakupuzzle.Coordinate{ 9, 9 }

    case 5:
      p.Width = 15
      p.Height = 15
      p.NumRegions = 38
      p.RegionSize = make([]int, 38)
      p.RegionSize[0] = 4
      p.RegionSize[1] = 6
      p.RegionSize[2] = 3
      p.RegionSize[3] = 4
      p.RegionSize[4] = 4
      p.RegionSize[5] = 4
      p.RegionSize[6] = 3
      p.RegionSize[7] = 2
      p.RegionSize[8] = 4
      p.RegionSize[9] = 2
      p.RegionSize[10] = 7
      p.RegionSize[11] = 3
      p.RegionSize[12] = 36
      p.RegionSize[13] = 18
      p.RegionSize[14] = 4
      p.RegionSize[15] = 3
      p.RegionSize[16] = 8
      p.RegionSize[17] = 2
      p.RegionSize[18] = 2
      p.RegionSize[19] = 3
      p.RegionSize[20] = 7
      p.RegionSize[21] = 2
      p.RegionSize[22] = 3
      p.RegionSize[23] = 32
      p.RegionSize[24] = 3
      p.RegionSize[25] = 8
      p.RegionSize[26] = 9
      p.RegionSize[27] = 2
      p.RegionSize[28] = 2
      p.RegionSize[29] = 2
      p.RegionSize[30] = 5
      p.RegionSize[31] = 2
      p.RegionSize[32] = 9
      p.RegionSize[33] = 3
      p.RegionSize[34] = 5
      p.RegionSize[35] = 2
      p.RegionSize[36] = 4
      p.RegionSize[37] = 3
      p.RegionLocation = make([]shikakupuzzle.Coordinate, 38)
      p.RegionLocation[0] = shikakupuzzle.Coordinate{ 0, 0 }
      p.RegionLocation[1] = shikakupuzzle.Coordinate{ 0, 7 }
      p.RegionLocation[2] = shikakupuzzle.Coordinate{ 0, 10 }
      p.RegionLocation[3] = shikakupuzzle.Coordinate{ 0, 13 }
      p.RegionLocation[4] = shikakupuzzle.Coordinate{ 1, 1 }
      p.RegionLocation[5] = shikakupuzzle.Coordinate{ 1, 2 }
      p.RegionLocation[6] = shikakupuzzle.Coordinate{ 1, 11 }
      p.RegionLocation[7] = shikakupuzzle.Coordinate{ 1, 14 }
      p.RegionLocation[8] = shikakupuzzle.Coordinate{ 2, 7 }
      p.RegionLocation[9] = shikakupuzzle.Coordinate{ 2, 9 }
      p.RegionLocation[10] = shikakupuzzle.Coordinate{ 2, 13 }
      p.RegionLocation[11] = shikakupuzzle.Coordinate{ 3, 12 }
      p.RegionLocation[12] = shikakupuzzle.Coordinate{ 4, 6 }
      p.RegionLocation[13] = shikakupuzzle.Coordinate{ 4, 8 }
      p.RegionLocation[14] = shikakupuzzle.Coordinate{ 5, 11 }
      p.RegionLocation[15] = shikakupuzzle.Coordinate{ 6, 0 }
      p.RegionLocation[16] = shikakupuzzle.Coordinate{ 6, 2 }
      p.RegionLocation[17] = shikakupuzzle.Coordinate{ 6, 12 }
      p.RegionLocation[18] = shikakupuzzle.Coordinate{ 7, 0 }
      p.RegionLocation[19] = shikakupuzzle.Coordinate{ 7, 7 }
      p.RegionLocation[20] = shikakupuzzle.Coordinate{ 7, 14 }
      p.RegionLocation[21] = shikakupuzzle.Coordinate{ 8, 2 }
      p.RegionLocation[22] = shikakupuzzle.Coordinate{ 8, 11 }
      p.RegionLocation[23] = shikakupuzzle.Coordinate{ 9, 5 }
      p.RegionLocation[24] = shikakupuzzle.Coordinate{ 9, 10 }
      p.RegionLocation[25] = shikakupuzzle.Coordinate{ 9, 13 }
      p.RegionLocation[26] = shikakupuzzle.Coordinate{ 10, 10 }
      p.RegionLocation[27] = shikakupuzzle.Coordinate{ 10, 14 }
      p.RegionLocation[28] = shikakupuzzle.Coordinate{ 12, 12 }
      p.RegionLocation[29] = shikakupuzzle.Coordinate{ 12, 13 }
      p.RegionLocation[30] = shikakupuzzle.Coordinate{ 13, 0 }
      p.RegionLocation[31] = shikakupuzzle.Coordinate{ 13, 2 }
      p.RegionLocation[32] = shikakupuzzle.Coordinate{ 13, 3 }
      p.RegionLocation[33] = shikakupuzzle.Coordinate{ 14, 2 }
      p.RegionLocation[34] = shikakupuzzle.Coordinate{ 14, 3 }
      p.RegionLocation[35] = shikakupuzzle.Coordinate{ 14, 9 }
      p.RegionLocation[36] = shikakupuzzle.Coordinate{ 14, 12 }
      p.RegionLocation[37] = shikakupuzzle.Coordinate{ 14, 14 }

    case 6:
      p.Width = 20
      p.Height = 20
      p.NumRegions = 57
      p.RegionSize = make([]int, 57)
      p.RegionSize[0] = 4
      p.RegionSize[1] = 2
      p.RegionSize[2] = 2
      p.RegionSize[3] = 3
      p.RegionSize[4] = 9
      p.RegionSize[5] = 12
      p.RegionSize[6] = 6
      p.RegionSize[7] = 2
      p.RegionSize[8] = 2
      p.RegionSize[9] = 24
      p.RegionSize[10] = 4
      p.RegionSize[11] = 3
      p.RegionSize[12] = 3
      p.RegionSize[13] = 3
      p.RegionSize[14] = 3
      p.RegionSize[15] = 3
      p.RegionSize[16] = 5
      p.RegionSize[17] = 2
      p.RegionSize[18] = 10
      p.RegionSize[19] = 2
      p.RegionSize[20] = 2
      p.RegionSize[21] = 35
      p.RegionSize[22] = 4
      p.RegionSize[23] = 30
      p.RegionSize[24] = 2
      p.RegionSize[25] = 7
      p.RegionSize[26] = 2
      p.RegionSize[27] = 20
      p.RegionSize[28] = 3
      p.RegionSize[29] = 2
      p.RegionSize[30] = 6
      p.RegionSize[31] = 11
      p.RegionSize[32] = 2
      p.RegionSize[33] = 2
      p.RegionSize[34] = 4
      p.RegionSize[35] = 2
      p.RegionSize[36] = 8
      p.RegionSize[37] = 10
      p.RegionSize[38] = 12
      p.RegionSize[39] = 3
      p.RegionSize[40] = 3
      p.RegionSize[41] = 45
      p.RegionSize[42] = 3
      p.RegionSize[43] = 2
      p.RegionSize[44] = 4
      p.RegionSize[45] = 10
      p.RegionSize[46] = 10
      p.RegionSize[47] = 2
      p.RegionSize[48] = 4
      p.RegionSize[49] = 3
      p.RegionSize[50] = 2
      p.RegionSize[51] = 14
      p.RegionSize[52] = 8
      p.RegionSize[53] = 2
      p.RegionSize[54] = 9
      p.RegionSize[55] = 5
      p.RegionSize[56] = 3
      p.RegionLocation = make([]shikakupuzzle.Coordinate, 57)
      p.RegionLocation[0] = shikakupuzzle.Coordinate{ 0, 13 }
      p.RegionLocation[1] = shikakupuzzle.Coordinate{ 0, 14 }
      p.RegionLocation[2] = shikakupuzzle.Coordinate{ 0, 18 }
      p.RegionLocation[3] = shikakupuzzle.Coordinate{ 1, 16 }
      p.RegionLocation[4] = shikakupuzzle.Coordinate{ 2, 1 }
      p.RegionLocation[5] = shikakupuzzle.Coordinate{ 2, 15 }
      p.RegionLocation[6] = shikakupuzzle.Coordinate{ 2, 19 }
      p.RegionLocation[7] = shikakupuzzle.Coordinate{ 3, 0 }
      p.RegionLocation[8] = shikakupuzzle.Coordinate{ 3, 1 }
      p.RegionLocation[9] = shikakupuzzle.Coordinate{ 3, 5 }
      p.RegionLocation[10] = shikakupuzzle.Coordinate{ 3, 9 }
      p.RegionLocation[11] = shikakupuzzle.Coordinate{ 3, 10 }
      p.RegionLocation[12] = shikakupuzzle.Coordinate{ 3, 14 }
      p.RegionLocation[13] = shikakupuzzle.Coordinate{ 4, 1 }
      p.RegionLocation[14] = shikakupuzzle.Coordinate{ 4, 4 }
      p.RegionLocation[15] = shikakupuzzle.Coordinate{ 4, 7 }
      p.RegionLocation[16] = shikakupuzzle.Coordinate{ 4, 16 }
      p.RegionLocation[17] = shikakupuzzle.Coordinate{ 4, 19 }
      p.RegionLocation[18] = shikakupuzzle.Coordinate{ 5, 18 }
      p.RegionLocation[19] = shikakupuzzle.Coordinate{ 5, 19 }
      p.RegionLocation[20] = shikakupuzzle.Coordinate{ 7, 1 }
      p.RegionLocation[21] = shikakupuzzle.Coordinate{ 7, 12 }
      p.RegionLocation[22] = shikakupuzzle.Coordinate{ 8, 0 }
      p.RegionLocation[23] = shikakupuzzle.Coordinate{ 8, 8 }
      p.RegionLocation[24] = shikakupuzzle.Coordinate{ 9, 0 }
      p.RegionLocation[25] = shikakupuzzle.Coordinate{ 9, 14 }
      p.RegionLocation[26] = shikakupuzzle.Coordinate{ 9, 16 }
      p.RegionLocation[27] = shikakupuzzle.Coordinate{ 9, 17 }
      p.RegionLocation[28] = shikakupuzzle.Coordinate{ 9, 19 }
      p.RegionLocation[29] = shikakupuzzle.Coordinate{ 10, 3 }
      p.RegionLocation[30] = shikakupuzzle.Coordinate{ 10, 5 }
      p.RegionLocation[31] = shikakupuzzle.Coordinate{ 10, 9 }
      p.RegionLocation[32] = shikakupuzzle.Coordinate{ 10, 19 }
      p.RegionLocation[33] = shikakupuzzle.Coordinate{ 11, 0 }
      p.RegionLocation[34] = shikakupuzzle.Coordinate{ 12, 15 }
      p.RegionLocation[35] = shikakupuzzle.Coordinate{ 13, 3 }
      p.RegionLocation[36] = shikakupuzzle.Coordinate{ 14, 0 }
      p.RegionLocation[37] = shikakupuzzle.Coordinate{ 14, 1 }
      p.RegionLocation[38] = shikakupuzzle.Coordinate{ 14, 2 }
      p.RegionLocation[39] = shikakupuzzle.Coordinate{ 14, 15 }
      p.RegionLocation[40] = shikakupuzzle.Coordinate{ 14, 19 }
      p.RegionLocation[41] = shikakupuzzle.Coordinate{ 15, 8 }
      p.RegionLocation[42] = shikakupuzzle.Coordinate{ 15, 16 }
      p.RegionLocation[43] = shikakupuzzle.Coordinate{ 15, 18 }
      p.RegionLocation[44] = shikakupuzzle.Coordinate{ 16, 3 }
      p.RegionLocation[45] = shikakupuzzle.Coordinate{ 16, 4 }
      p.RegionLocation[46] = shikakupuzzle.Coordinate{ 16, 11 }
      p.RegionLocation[47] = shikakupuzzle.Coordinate{ 16, 15 }
      p.RegionLocation[48] = shikakupuzzle.Coordinate{ 17, 2 }
      p.RegionLocation[49] = shikakupuzzle.Coordinate{ 17, 5 }
      p.RegionLocation[50] = shikakupuzzle.Coordinate{ 17, 9 }
      p.RegionLocation[51] = shikakupuzzle.Coordinate{ 17, 11 }
      p.RegionLocation[52] = shikakupuzzle.Coordinate{ 17, 18 }
      p.RegionLocation[53] = shikakupuzzle.Coordinate{ 18, 3 }
      p.RegionLocation[54] = shikakupuzzle.Coordinate{ 19, 7 }
      p.RegionLocation[55] = shikakupuzzle.Coordinate{ 19, 13 }
      p.RegionLocation[56] = shikakupuzzle.Coordinate{ 19, 16 }

    case 7:
      p.Width = 25
      p.Height = 25
      p.NumRegions = 84
      p.RegionSize = make([]int, 84)
      p.RegionSize[0] = 4
      p.RegionSize[1] = 14
      p.RegionSize[2] = 2
      p.RegionSize[3] = 18
      p.RegionSize[4] = 2
      p.RegionSize[5] = 2
      p.RegionSize[6] = 2
      p.RegionSize[7] = 2
      p.RegionSize[8] = 45
      p.RegionSize[9] = 2
      p.RegionSize[10] = 3
      p.RegionSize[11] = 10
      p.RegionSize[12] = 2
      p.RegionSize[13] = 4
      p.RegionSize[14] = 2
      p.RegionSize[15] = 2
      p.RegionSize[16] = 3
      p.RegionSize[17] = 6
      p.RegionSize[18] = 3
      p.RegionSize[19] = 14
      p.RegionSize[20] = 5
      p.RegionSize[21] = 2
      p.RegionSize[22] = 2
      p.RegionSize[23] = 6
      p.RegionSize[24] = 18
      p.RegionSize[25] = 2
      p.RegionSize[26] = 16
      p.RegionSize[27] = 3
      p.RegionSize[28] = 2
      p.RegionSize[29] = 5
      p.RegionSize[30] = 4
      p.RegionSize[31] = 2
      p.RegionSize[32] = 8
      p.RegionSize[33] = 2
      p.RegionSize[34] = 22
      p.RegionSize[35] = 15
      p.RegionSize[36] = 2
      p.RegionSize[37] = 2
      p.RegionSize[38] = 2
      p.RegionSize[39] = 10
      p.RegionSize[40] = 10
      p.RegionSize[41] = 2
      p.RegionSize[42] = 6
      p.RegionSize[43] = 3
      p.RegionSize[44] = 10
      p.RegionSize[45] = 9
      p.RegionSize[46] = 45
      p.RegionSize[47] = 2
      p.RegionSize[48] = 2
      p.RegionSize[49] = 78
      p.RegionSize[50] = 3
      p.RegionSize[51] = 3
      p.RegionSize[52] = 3
      p.RegionSize[53] = 24
      p.RegionSize[54] = 2
      p.RegionSize[55] = 3
      p.RegionSize[56] = 28
      p.RegionSize[57] = 2
      p.RegionSize[58] = 2
      p.RegionSize[59] = 2
      p.RegionSize[60] = 6
      p.RegionSize[61] = 2
      p.RegionSize[62] = 2
      p.RegionSize[63] = 7
      p.RegionSize[64] = 2
      p.RegionSize[65] = 2
      p.RegionSize[66] = 2
      p.RegionSize[67] = 2
      p.RegionSize[68] = 4
      p.RegionSize[69] = 3
      p.RegionSize[70] = 15
      p.RegionSize[71] = 2
      p.RegionSize[72] = 2
      p.RegionSize[73] = 5
      p.RegionSize[74] = 18
      p.RegionSize[75] = 7
      p.RegionSize[76] = 4
      p.RegionSize[77] = 2
      p.RegionSize[78] = 3
      p.RegionSize[79] = 2
      p.RegionSize[80] = 8
      p.RegionSize[81] = 6
      p.RegionSize[82] = 2
      p.RegionSize[83] = 6
      p.RegionLocation = make([]shikakupuzzle.Coordinate, 84)
      p.RegionLocation[0] = shikakupuzzle.Coordinate{ 0, 2 }
      p.RegionLocation[1] = shikakupuzzle.Coordinate{ 0, 5 }
      p.RegionLocation[2] = shikakupuzzle.Coordinate{ 0, 13 }
      p.RegionLocation[3] = shikakupuzzle.Coordinate{ 0, 21 }
      p.RegionLocation[4] = shikakupuzzle.Coordinate{ 0, 23 }
      p.RegionLocation[5] = shikakupuzzle.Coordinate{ 1, 4 }
      p.RegionLocation[6] = shikakupuzzle.Coordinate{ 1, 13 }
      p.RegionLocation[7] = shikakupuzzle.Coordinate{ 1, 23 }
      p.RegionLocation[8] = shikakupuzzle.Coordinate{ 2, 4 }
      p.RegionLocation[9] = shikakupuzzle.Coordinate{ 2, 17 }
      p.RegionLocation[10] = shikakupuzzle.Coordinate{ 2, 19 }
      p.RegionLocation[11] = shikakupuzzle.Coordinate{ 3, 0 }
      p.RegionLocation[12] = shikakupuzzle.Coordinate{ 3, 20 }
      p.RegionLocation[13] = shikakupuzzle.Coordinate{ 3, 22 }
      p.RegionLocation[14] = shikakupuzzle.Coordinate{ 4, 17 }
      p.RegionLocation[15] = shikakupuzzle.Coordinate{ 4, 18 }
      p.RegionLocation[16] = shikakupuzzle.Coordinate{ 4, 20 }
      p.RegionLocation[17] = shikakupuzzle.Coordinate{ 4, 24 }
      p.RegionLocation[18] = shikakupuzzle.Coordinate{ 5, 1 }
      p.RegionLocation[19] = shikakupuzzle.Coordinate{ 5, 9 }
      p.RegionLocation[20] = shikakupuzzle.Coordinate{ 5, 23 }
      p.RegionLocation[21] = shikakupuzzle.Coordinate{ 6, 0 }
      p.RegionLocation[22] = shikakupuzzle.Coordinate{ 6, 14 }
      p.RegionLocation[23] = shikakupuzzle.Coordinate{ 6, 15 }
      p.RegionLocation[24] = shikakupuzzle.Coordinate{ 7, 1 }
      p.RegionLocation[25] = shikakupuzzle.Coordinate{ 7, 4 }
      p.RegionLocation[26] = shikakupuzzle.Coordinate{ 7, 12 }
      p.RegionLocation[27] = shikakupuzzle.Coordinate{ 7, 23 }
      p.RegionLocation[28] = shikakupuzzle.Coordinate{ 8, 6 }
      p.RegionLocation[29] = shikakupuzzle.Coordinate{ 8, 9 }
      p.RegionLocation[30] = shikakupuzzle.Coordinate{ 8, 13 }
      p.RegionLocation[31] = shikakupuzzle.Coordinate{ 8, 24 }
      p.RegionLocation[32] = shikakupuzzle.Coordinate{ 10, 5 }
      p.RegionLocation[33] = shikakupuzzle.Coordinate{ 10, 24 }
      p.RegionLocation[34] = shikakupuzzle.Coordinate{ 11, 3 }
      p.RegionLocation[35] = shikakupuzzle.Coordinate{ 11, 8 }
      p.RegionLocation[36] = shikakupuzzle.Coordinate{ 11, 23 }
      p.RegionLocation[37] = shikakupuzzle.Coordinate{ 12, 23 }
      p.RegionLocation[38] = shikakupuzzle.Coordinate{ 13, 4 }
      p.RegionLocation[39] = shikakupuzzle.Coordinate{ 13, 9 }
      p.RegionLocation[40] = shikakupuzzle.Coordinate{ 13, 23 }
      p.RegionLocation[41] = shikakupuzzle.Coordinate{ 13, 24 }
      p.RegionLocation[42] = shikakupuzzle.Coordinate{ 14, 6 }
      p.RegionLocation[43] = shikakupuzzle.Coordinate{ 14, 10 }
      p.RegionLocation[44] = shikakupuzzle.Coordinate{ 15, 9 }
      p.RegionLocation[45] = shikakupuzzle.Coordinate{ 15, 11 }
      p.RegionLocation[46] = shikakupuzzle.Coordinate{ 15, 13 }
      p.RegionLocation[47] = shikakupuzzle.Coordinate{ 16, 1 }
      p.RegionLocation[48] = shikakupuzzle.Coordinate{ 16, 4 }
      p.RegionLocation[49] = shikakupuzzle.Coordinate{ 16, 19 }
      p.RegionLocation[50] = shikakupuzzle.Coordinate{ 16, 24 }
      p.RegionLocation[51] = shikakupuzzle.Coordinate{ 17, 8 }
      p.RegionLocation[52] = shikakupuzzle.Coordinate{ 17, 10 }
      p.RegionLocation[53] = shikakupuzzle.Coordinate{ 18, 5 }
      p.RegionLocation[54] = shikakupuzzle.Coordinate{ 18, 22 }
      p.RegionLocation[55] = shikakupuzzle.Coordinate{ 19, 6 }
      p.RegionLocation[56] = shikakupuzzle.Coordinate{ 19, 12 }
      p.RegionLocation[57] = shikakupuzzle.Coordinate{ 19, 22 }
      p.RegionLocation[58] = shikakupuzzle.Coordinate{ 19, 24 }
      p.RegionLocation[59] = shikakupuzzle.Coordinate{ 20, 6 }
      p.RegionLocation[60] = shikakupuzzle.Coordinate{ 20, 18 }
      p.RegionLocation[61] = shikakupuzzle.Coordinate{ 20, 21 }
      p.RegionLocation[62] = shikakupuzzle.Coordinate{ 21, 0 }
      p.RegionLocation[63] = shikakupuzzle.Coordinate{ 21, 2 }
      p.RegionLocation[64] = shikakupuzzle.Coordinate{ 21, 8 }
      p.RegionLocation[65] = shikakupuzzle.Coordinate{ 21, 9 }
      p.RegionLocation[66] = shikakupuzzle.Coordinate{ 21, 10 }
      p.RegionLocation[67] = shikakupuzzle.Coordinate{ 21, 11 }
      p.RegionLocation[68] = shikakupuzzle.Coordinate{ 21, 13 }
      p.RegionLocation[69] = shikakupuzzle.Coordinate{ 21, 15 }
      p.RegionLocation[70] = shikakupuzzle.Coordinate{ 21, 18 }
      p.RegionLocation[71] = shikakupuzzle.Coordinate{ 21, 24 }
      p.RegionLocation[72] = shikakupuzzle.Coordinate{ 22, 1 }
      p.RegionLocation[73] = shikakupuzzle.Coordinate{ 22, 7 }
      p.RegionLocation[74] = shikakupuzzle.Coordinate{ 22, 15 }
      p.RegionLocation[75] = shikakupuzzle.Coordinate{ 23, 2 }
      p.RegionLocation[76] = shikakupuzzle.Coordinate{ 23, 22 }
      p.RegionLocation[77] = shikakupuzzle.Coordinate{ 23, 23 }
      p.RegionLocation[78] = shikakupuzzle.Coordinate{ 23, 24 }
      p.RegionLocation[79] = shikakupuzzle.Coordinate{ 24, 0 }
      p.RegionLocation[80] = shikakupuzzle.Coordinate{ 24, 8 }
      p.RegionLocation[81] = shikakupuzzle.Coordinate{ 24, 9 }
      p.RegionLocation[82] = shikakupuzzle.Coordinate{ 24, 16 }
      p.RegionLocation[83] = shikakupuzzle.Coordinate{ 24, 18 }

    case 8:
      p.Width = 30
      p.Height = 30
      p.NumRegions = 107
      p.RegionSize = make([]int, 107)
      p.RegionSize[0] = 11
      p.RegionSize[1] = 3
      p.RegionSize[2] = 4
      p.RegionSize[3] = 12
      p.RegionSize[4] = 3
      p.RegionSize[5] = 3
      p.RegionSize[6] = 5
      p.RegionSize[7] = 2
      p.RegionSize[8] = 7
      p.RegionSize[9] = 2
      p.RegionSize[10] = 2
      p.RegionSize[11] = 4
      p.RegionSize[12] = 2
      p.RegionSize[13] = 4
      p.RegionSize[14] = 12
      p.RegionSize[15] = 2
      p.RegionSize[16] = 2
      p.RegionSize[17] = 3
      p.RegionSize[18] = 2
      p.RegionSize[19] = 36
      p.RegionSize[20] = 2
      p.RegionSize[21] = 2
      p.RegionSize[22] = 4
      p.RegionSize[23] = 12
      p.RegionSize[24] = 10
      p.RegionSize[25] = 4
      p.RegionSize[26] = 2
      p.RegionSize[27] = 16
      p.RegionSize[28] = 16
      p.RegionSize[29] = 6
      p.RegionSize[30] = 2
      p.RegionSize[31] = 4
      p.RegionSize[32] = 3
      p.RegionSize[33] = 6
      p.RegionSize[34] = 2
      p.RegionSize[35] = 9
      p.RegionSize[36] = 55
      p.RegionSize[37] = 6
      p.RegionSize[38] = 5
      p.RegionSize[39] = 3
      p.RegionSize[40] = 4
      p.RegionSize[41] = 7
      p.RegionSize[42] = 3
      p.RegionSize[43] = 8
      p.RegionSize[44] = 5
      p.RegionSize[45] = 2
      p.RegionSize[46] = 2
      p.RegionSize[47] = 2
      p.RegionSize[48] = 2
      p.RegionSize[49] = 8
      p.RegionSize[50] = 3
      p.RegionSize[51] = 6
      p.RegionSize[52] = 12
      p.RegionSize[53] = 2
      p.RegionSize[54] = 10
      p.RegionSize[55] = 2
      p.RegionSize[56] = 26
      p.RegionSize[57] = 6
      p.RegionSize[58] = 3
      p.RegionSize[59] = 4
      p.RegionSize[60] = 8
      p.RegionSize[61] = 2
      p.RegionSize[62] = 2
      p.RegionSize[63] = 3
      p.RegionSize[64] = 2
      p.RegionSize[65] = 16
      p.RegionSize[66] = 3
      p.RegionSize[67] = 14
      p.RegionSize[68] = 2
      p.RegionSize[69] = 2
      p.RegionSize[70] = 2
      p.RegionSize[71] = 16
      p.RegionSize[72] = 120
      p.RegionSize[73] = 12
      p.RegionSize[74] = 2
      p.RegionSize[75] = 27
      p.RegionSize[76] = 8
      p.RegionSize[77] = 2
      p.RegionSize[78] = 10
      p.RegionSize[79] = 6
      p.RegionSize[80] = 13
      p.RegionSize[81] = 2
      p.RegionSize[82] = 2
      p.RegionSize[83] = 8
      p.RegionSize[84] = 2
      p.RegionSize[85] = 5
      p.RegionSize[86] = 6
      p.RegionSize[87] = 112
      p.RegionSize[88] = 2
      p.RegionSize[89] = 12
      p.RegionSize[90] = 6
      p.RegionSize[91] = 2
      p.RegionSize[92] = 2
      p.RegionSize[93] = 2
      p.RegionSize[94] = 5
      p.RegionSize[95] = 2
      p.RegionSize[96] = 2
      p.RegionSize[97] = 3
      p.RegionSize[98] = 2
      p.RegionSize[99] = 2
      p.RegionSize[100] = 8
      p.RegionSize[101] = 3
      p.RegionSize[102] = 4
      p.RegionSize[103] = 4
      p.RegionSize[104] = 5
      p.RegionSize[105] = 5
      p.RegionSize[106] = 13
      p.RegionLocation = make([]shikakupuzzle.Coordinate, 107)
      p.RegionLocation[0] = shikakupuzzle.Coordinate{ 0, 0 }
      p.RegionLocation[1] = shikakupuzzle.Coordinate{ 0, 2 }
      p.RegionLocation[2] = shikakupuzzle.Coordinate{ 0, 4 }
      p.RegionLocation[3] = shikakupuzzle.Coordinate{ 0, 11 }
      p.RegionLocation[4] = shikakupuzzle.Coordinate{ 0, 20 }
      p.RegionLocation[5] = shikakupuzzle.Coordinate{ 0, 22 }
      p.RegionLocation[6] = shikakupuzzle.Coordinate{ 0, 25 }
      p.RegionLocation[7] = shikakupuzzle.Coordinate{ 1, 1 }
      p.RegionLocation[8] = shikakupuzzle.Coordinate{ 1, 18 }
      p.RegionLocation[9] = shikakupuzzle.Coordinate{ 1, 23 }
      p.RegionLocation[10] = shikakupuzzle.Coordinate{ 2, 3 }
      p.RegionLocation[11] = shikakupuzzle.Coordinate{ 2, 13 }
      p.RegionLocation[12] = shikakupuzzle.Coordinate{ 2, 14 }
      p.RegionLocation[13] = shikakupuzzle.Coordinate{ 2, 27 }
      p.RegionLocation[14] = shikakupuzzle.Coordinate{ 3, 12 }
      p.RegionLocation[15] = shikakupuzzle.Coordinate{ 3, 23 }
      p.RegionLocation[16] = shikakupuzzle.Coordinate{ 3, 26 }
      p.RegionLocation[17] = shikakupuzzle.Coordinate{ 4, 12 }
      p.RegionLocation[18] = shikakupuzzle.Coordinate{ 4, 14 }
      p.RegionLocation[19] = shikakupuzzle.Coordinate{ 4, 19 }
      p.RegionLocation[20] = shikakupuzzle.Coordinate{ 4, 22 }
      p.RegionLocation[21] = shikakupuzzle.Coordinate{ 4, 23 }
      p.RegionLocation[22] = shikakupuzzle.Coordinate{ 4, 27 }
      p.RegionLocation[23] = shikakupuzzle.Coordinate{ 4, 28 }
      p.RegionLocation[24] = shikakupuzzle.Coordinate{ 5, 24 }
      p.RegionLocation[25] = shikakupuzzle.Coordinate{ 6, 25 }
      p.RegionLocation[26] = shikakupuzzle.Coordinate{ 6, 28 }
      p.RegionLocation[27] = shikakupuzzle.Coordinate{ 7, 3 }
      p.RegionLocation[28] = shikakupuzzle.Coordinate{ 7, 11 }
      p.RegionLocation[29] = shikakupuzzle.Coordinate{ 7, 21 }
      p.RegionLocation[30] = shikakupuzzle.Coordinate{ 7, 24 }
      p.RegionLocation[31] = shikakupuzzle.Coordinate{ 8, 10 }
      p.RegionLocation[32] = shikakupuzzle.Coordinate{ 8, 16 }
      p.RegionLocation[33] = shikakupuzzle.Coordinate{ 8, 21 }
      p.RegionLocation[34] = shikakupuzzle.Coordinate{ 8, 23 }
      p.RegionLocation[35] = shikakupuzzle.Coordinate{ 9, 1 }
      p.RegionLocation[36] = shikakupuzzle.Coordinate{ 9, 4 }
      p.RegionLocation[37] = shikakupuzzle.Coordinate{ 9, 9 }
      p.RegionLocation[38] = shikakupuzzle.Coordinate{ 9, 12 }
      p.RegionLocation[39] = shikakupuzzle.Coordinate{ 9, 16 }
      p.RegionLocation[40] = shikakupuzzle.Coordinate{ 9, 19 }
      p.RegionLocation[41] = shikakupuzzle.Coordinate{ 9, 26 }
      p.RegionLocation[42] = shikakupuzzle.Coordinate{ 10, 9 }
      p.RegionLocation[43] = shikakupuzzle.Coordinate{ 10, 12 }
      p.RegionLocation[44] = shikakupuzzle.Coordinate{ 10, 22 }
      p.RegionLocation[45] = shikakupuzzle.Coordinate{ 11, 0 }
      p.RegionLocation[46] = shikakupuzzle.Coordinate{ 11, 2 }
      p.RegionLocation[47] = shikakupuzzle.Coordinate{ 11, 10 }
      p.RegionLocation[48] = shikakupuzzle.Coordinate{ 11, 11 }
      p.RegionLocation[49] = shikakupuzzle.Coordinate{ 11, 19 }
      p.RegionLocation[50] = shikakupuzzle.Coordinate{ 11, 23 }
      p.RegionLocation[51] = shikakupuzzle.Coordinate{ 11, 24 }
      p.RegionLocation[52] = shikakupuzzle.Coordinate{ 12, 9 }
      p.RegionLocation[53] = shikakupuzzle.Coordinate{ 12, 13 }
      p.RegionLocation[54] = shikakupuzzle.Coordinate{ 12, 14 }
      p.RegionLocation[55] = shikakupuzzle.Coordinate{ 12, 26 }
      p.RegionLocation[56] = shikakupuzzle.Coordinate{ 12, 28 }
      p.RegionLocation[57] = shikakupuzzle.Coordinate{ 13, 6 }
      p.RegionLocation[58] = shikakupuzzle.Coordinate{ 13, 7 }
      p.RegionLocation[59] = shikakupuzzle.Coordinate{ 13, 13 }
      p.RegionLocation[60] = shikakupuzzle.Coordinate{ 14, 0 }
      p.RegionLocation[61] = shikakupuzzle.Coordinate{ 14, 6 }
      p.RegionLocation[62] = shikakupuzzle.Coordinate{ 14, 8 }
      p.RegionLocation[63] = shikakupuzzle.Coordinate{ 14, 11 }
      p.RegionLocation[64] = shikakupuzzle.Coordinate{ 14, 12 }
      p.RegionLocation[65] = shikakupuzzle.Coordinate{ 15, 1 }
      p.RegionLocation[66] = shikakupuzzle.Coordinate{ 15, 24 }
      p.RegionLocation[67] = shikakupuzzle.Coordinate{ 17, 29 }
      p.RegionLocation[68] = shikakupuzzle.Coordinate{ 18, 2 }
      p.RegionLocation[69] = shikakupuzzle.Coordinate{ 18, 3 }
      p.RegionLocation[70] = shikakupuzzle.Coordinate{ 19, 4 }
      p.RegionLocation[71] = shikakupuzzle.Coordinate{ 19, 25 }
      p.RegionLocation[72] = shikakupuzzle.Coordinate{ 20, 14 }
      p.RegionLocation[73] = shikakupuzzle.Coordinate{ 20, 26 }
      p.RegionLocation[74] = shikakupuzzle.Coordinate{ 20, 27 }
      p.RegionLocation[75] = shikakupuzzle.Coordinate{ 21, 3 }
      p.RegionLocation[76] = shikakupuzzle.Coordinate{ 21, 24 }
      p.RegionLocation[77] = shikakupuzzle.Coordinate{ 21, 28 }
      p.RegionLocation[78] = shikakupuzzle.Coordinate{ 22, 0 }
      p.RegionLocation[79] = shikakupuzzle.Coordinate{ 23, 4 }
      p.RegionLocation[80] = shikakupuzzle.Coordinate{ 23, 5 }
      p.RegionLocation[81] = shikakupuzzle.Coordinate{ 23, 29 }
      p.RegionLocation[82] = shikakupuzzle.Coordinate{ 24, 25 }
      p.RegionLocation[83] = shikakupuzzle.Coordinate{ 25, 22 }
      p.RegionLocation[84] = shikakupuzzle.Coordinate{ 25, 24 }
      p.RegionLocation[85] = shikakupuzzle.Coordinate{ 25, 28 }
      p.RegionLocation[86] = shikakupuzzle.Coordinate{ 25, 29 }
      p.RegionLocation[87] = shikakupuzzle.Coordinate{ 26, 8 }
      p.RegionLocation[88] = shikakupuzzle.Coordinate{ 26, 14 }
      p.RegionLocation[89] = shikakupuzzle.Coordinate{ 26, 18 }
      p.RegionLocation[90] = shikakupuzzle.Coordinate{ 26, 27 }
      p.RegionLocation[91] = shikakupuzzle.Coordinate{ 27, 15 }
      p.RegionLocation[92] = shikakupuzzle.Coordinate{ 27, 16 }
      p.RegionLocation[93] = shikakupuzzle.Coordinate{ 27, 18 }
      p.RegionLocation[94] = shikakupuzzle.Coordinate{ 27, 22 }
      p.RegionLocation[95] = shikakupuzzle.Coordinate{ 27, 27 }
      p.RegionLocation[96] = shikakupuzzle.Coordinate{ 27, 28 }
      p.RegionLocation[97] = shikakupuzzle.Coordinate{ 28, 2 }
      p.RegionLocation[98] = shikakupuzzle.Coordinate{ 28, 4 }
      p.RegionLocation[99] = shikakupuzzle.Coordinate{ 28, 5 }
      p.RegionLocation[100] = shikakupuzzle.Coordinate{ 28, 17 }
      p.RegionLocation[101] = shikakupuzzle.Coordinate{ 28, 24 }
      p.RegionLocation[102] = shikakupuzzle.Coordinate{ 28, 26 }
      p.RegionLocation[103] = shikakupuzzle.Coordinate{ 29, 2 }
      p.RegionLocation[104] = shikakupuzzle.Coordinate{ 29, 7 }
      p.RegionLocation[105] = shikakupuzzle.Coordinate{ 29, 14 }
      p.RegionLocation[106] = shikakupuzzle.Coordinate{ 29, 28 }
  }
  a := make(shikakupuzzle.ShikakuState)

  p.Print(a)
  
  fmt.Printf("Starting search\n")
  start := time.Now()
  solution := search.Search(&p)
  elapsed := time.Since(start)
  
  fmt.Printf("\nSolution found\n\n")
  p.Print(solution)
  
  fmt.Printf("\nElapsed time: %f\n", elapsed.Seconds())
  
  if !p.IsSolved(solution) {
    fmt.Printf("Not a correct solution\n")
  } else {
    fmt.Printf("Solution is correct\n")
  }
}
